#!/usr/bin/env bash


# brew install netpbm

for i in `ls support/artworks/*.jpg`; do
    echo $(basename $i)
    jpegtopnm $i | pamscale -xyfit 400 240 | pamditherbw -atkinson | pamtopng > source/images/artworks/full/$(basename $i .jpg).png
    jpegtopnm $i | pamscale -xyfit 366 166 | pamditherbw -atkinson | pamtopng > source/images/artworks/small/$(basename $i .jpg).png
done
